stages:
  - build
  - clear

build:
  stage: build
  image: node:lts
  rules:
    - changes:
        - .gitignore
        - .gitlab-ci.yml
        - LICENSE.md
        - README.md
      when: never
    - changes:
        - src/**/*
        - static/**/*
        - astro.config.ts
        - package.json
        - package-lock.json
      when: on_success
    - when: manual
  before_script:
    - npm ci
    - npm i wrangler --location=global
  script:
    - echo "CI_PIPELINE_SOURCE=$CI_PIPELINE_SOURCE"
    - echo "CI_COMMIT_REF_NAME=$CI_COMMIT_REF_NAME"
    - echo "CI_COMMIT_BRANCH=$CI_COMMIT_BRANCH"
    - echo "CI_MERGE_REQUEST_SOURCE_BRANCH_NAME=$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME"
    - 'export PAGES_BRANCH="${CI_MERGE_REQUEST_SOURCE_BRANCH_NAME:-$CI_COMMIT_REF_NAME}"'
    - 'echo "Deploying Cloudflare Pages branch: $PAGES_BRANCH"'
    - npm run build
    - wrangler pages deploy ./public --project-name "nrp-portal" --branch "$PAGES_BRANCH"

clear:
  stage: clear
  image: ubuntu:latest
  script:
    - ./clear-cloudflare.sh
