stages:
  - build
  - deploy

build:
  stage: build
  image: node:lts
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never
    - changes:
        - .gitignore
        - .gitlab-ci.yml
        - LICENSE.md
        - README.md
      when: never
  before_script:
    - npm ci
    - npm i wrangler --location=global
  script:
    - npm run build
    - wrangler pages deploy ./public --project-name "nrp-portal" --branch "$CI_COMMIT_REF_NAME"